Q1. Get the positions where elements of a and b match Input:

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

Output:

(array([1, 3, 5, 7]),)

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [3]:
np.where(a==b,)

(array([1, 3, 5, 7]),)

Q2. Get all items between 5 and 10 from a.

a = np.array([2, 6, 1, 9, 10, 3, 27])

In [4]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [5]:
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

Q3. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)

In [6]:
arr = np.arange(9).reshape(3,3)

In [7]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr[:,[0,1]] = arr[:,[1,0]]

In [9]:
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Q4. Reverse the rows of a 2D array arr.

arr = np.arange(9).reshape(3,3)

In [10]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
arr[[0,1,2],:] = arr[[2,1,0],:]

In [12]:
arr

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

Q5. Find the 5th and 95th percentile of iris's sepallength Note - Find input code in the next cell

In [13]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength

# Write code for Q5 here

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [14]:
print("5th percentile value is",np.percentile(sepallength,5))
print("95th percentile value is",np.percentile(sepallength,95))

5th percentile value is 4.6
95th percentile value is 7.254999999999998


In [15]:
# This is the input of your question
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

sepalLength=iris_2d[:,0]
# This is the sepalLength
sepalLength

# Write your code here
# Hint - You can use the isNan() function.

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, nan, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, nan, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, nan, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, nan, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, nan, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [16]:
sepalLength[np.isnan(sepalLength)] = 0


In [17]:
np.where(sepalLength==0,)

(array([ 14,  47,  98, 108, 121]),)

Q7 .Replace all the null values with 0 in the above used sepalLength array

In [18]:
sepalLength[np.isnan(sepalLength)] = 0

In [19]:
sepalLength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 0. , 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 0. , 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 0. , 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 0. , 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 0. , 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

Q8. Find the 2nd largest value for the given array.

In [20]:
# Input
arr=np.random.randint(23,78, size=9).reshape(3,3)
arr

# Write your code here

array([[74, 61, 24],
       [39, 30, 72],
       [77, 24, 27]])

In [21]:
f = arr.flatten() ## 1d formation
f.sort() ##sorting
f[-2] ## negative indexing for max and 2 for second max

74

Q9. From the array a, replace all values greater than 30 by 30 and less than 10 by 10.

In [23]:
a=np.random.randint(1,78, size=9).reshape(3,3)
a

array([[33, 52, 38],
       [ 6, 20, 56],
       [24, 28, 59]])

In [24]:
a[(a>=30)]=30
a[(a<=10)]=10

Q10. Drop all nan values from a 1D numpy array



In [25]:
arr=np.array([1,2,3,np.nan,5,6,7,np.nan])
arr

# Write code here

array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan])

In [26]:
arr[np.logical_not(np.isnan(arr))] ## logical not work like not gate its changes 0 to 1 and vicevarsa

array([1., 2., 3., 5., 6., 7.])