In [51]:
import numpy as np

In [52]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Q1.Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])

In [53]:
# without using fancy indexing
arrx = np.copy(arr1)
x = np.copy(arrx[:,0])
arrx[:,0] = arrx[:,3]
arrx[:,3] = x

arrx

array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])

In [54]:
## using Fancy Indexing
arry = np.copy(arr1)
arry[:,[0,3]] = arry[:,[3,0]]
arry

array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])

Q2.Write a numpy code to reverse the rows of arr1

The output should be [15, 16, 17, 18, 19] as first row and [ 0, 1, 2, 3, 4] as last row

In [55]:
## without fancy indexing
l = [] # initilizing empty list
i = len(arr1)-1 ## initizing loop variable 
while i>=0:
    l.append(arr1[i,:]) 
    y = np.array(l)
    i = i-1
print(y)
type(y)

[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


numpy.ndarray

In [56]:
## using fancy indexing
arrt = np.copy(arr1)
arrt[[0,1,2,3],:] = arrt[[3,2,1,0],:]
arrt

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

Q3.Write a code to replace all the nan(missing values) of arr2 with the mean of arr2

In [57]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [58]:
arr2[np.isnan(arr2)] = np.nanmean(arr2)
arr2

array([[1. , 2. , 4.5],
       [4. , 5. , 6. ],
       [4.5, 4.5, 9. ]])

Q4.Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3

In [60]:
arr3[(arr3>25) | (arr3%3==0)]

array([45, 31, 78, 89, 48, 90,  3, 60, 39, 49, 34, 31, 99, 82, 63, 29,  3])

In [59]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[45, 31, 25, 78],
       [89, 48, 90,  3],
       [60, 39, 49, 34],
       [ 8, 31, 99,  8],
       [82, 63, 29,  3]])

Q5.Write a code to find the 10th, 25th, 50th(median) percentile of arr3

Percentiles are a very important concept in Statistics.



In [61]:
print("10th percentile value is",np.percentile(arr3,10))
print("25th percentile value is",np.percentile(arr3,25))
print("50th percentile value is",np.percentile(arr3,50))

10th percentile value is 7.500000000000001
25th percentile value is 28.0
50th percentile value is 42.0
